=== ryanwli/guzz/src/main/resources/META-INF/guzz.dtd
<!--
	Guzz main config DTD, version 1.0
	Authors: Liu Kaixuan (liukaixuan@gmail.com)

	<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//MAIN CONFIG DTD//EN" "http://www.guzz.org/dtd/guzz.dtd">
-->
<!--
	The document root.
-->
<!ELEMENT guzz-configs (config-server? | tran? | dialect| service | import | business | a-business | business-scan | sqlMap | orm)*>

<!ELEMENT properties EMPTY>
<!ATTLIST properties file CDATA #REQUIRED>

<!ELEMENT config-server (server+)>
<!ELEMENT server (param*)>
<!ATTLIST server class CDATA #REQUIRED>
<!ELEMENT param EMPTY>
<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #REQUIRED>

<!ELEMENT tran ((dbgroup* | virtualdbgroup*)+)>
<!ATTLIST tran locator CDATA "default">

<!ELEMENT virtualdbgroup (dbgroup*)>
<!ATTLIST virtualdbgroup name CDATA #REQUIRED>
<!ATTLIST virtualdbgroup dialectName CDATA "default">
<!ATTLIST virtualdbgroup shadow CDATA #REQUIRED>

<!ELEMENT dbgroup EMPTY>
<!ATTLIST dbgroup name CDATA "default">
<!ATTLIST dbgroup masterDBConfigName CDATA #IMPLIED>
<!ATTLIST dbgroup slaveDBConfigName CDATA #IMPLIED>
<!ATTLIST dbgroup dialectName CDATA "default">


<!ELEMENT dialect (type*)>
<!ATTLIST dialect name CDATA "default">
<!ATTLIST dialect class CDATA #REQUIRED>
<!ELEMENT type EMPTY>
<!ATTLIST type name CDATA #REQUIRED>
<!ATTLIST type class CDATA #REQUIRED>


<!ELEMENT service EMPTY>
<!ATTLIST service name CDATA #REQUIRED>
<!ATTLIST service configName CDATA #IMPLIED>
<!ATTLIST service class CDATA #REQUIRED>
<!ATTLIST service dependsOn CDATA #IMPLIED>


<!ELEMENT import EMPTY>
<!ATTLIST import resource CDATA #REQUIRED>


<!ELEMENT business EMPTY>
<!ATTLIST business name CDATA #REQUIRED>
<!ATTLIST business dbgroup CDATA "default">
<!ATTLIST business class CDATA #IMPLIED>
<!ATTLIST business interpret CDATA #IMPLIED>
<!ATTLIST business file CDATA #REQUIRED>

<!ELEMENT a-business EMPTY>
<!ATTLIST a-business name CDATA #IMPLIED>
<!ATTLIST a-business dbgroup CDATA "default">
<!ATTLIST a-business class CDATA #REQUIRED>

<!ELEMENT business-scan EMPTY>
<!ATTLIST business-scan dbgroup CDATA "default">
<!ATTLIST business-scan resources CDATA #REQUIRED>

<!ELEMENT sqlMap ((select | update | orm)*)>
<!ATTLIST sqlMap dbgroup CDATA "default">

<!ELEMENT select (#PCDATA|paramsMapping)*>
<!ELEMENT paramsMapping (map*)>
<!ELEMENT map EMPTY>
<!ATTLIST map paramName CDATA #REQUIRED>
<!ATTLIST map propName CDATA #IMPLIED>
<!ATTLIST map type CDATA #IMPLIED>
<!ATTLIST select id ID #REQUIRED>
<!ATTLIST select orm CDATA #REQUIRED>
<!ATTLIST select result-class CDATA #IMPLIED>
<!ATTLIST select templated (true|false) "false">

<!ELEMENT update (#PCDATA|paramsMapping)*>
<!ATTLIST update id ID #REQUIRED>
<!ATTLIST update orm CDATA #REQUIRED>
<!ATTLIST update templated (true|false) "false">

<!ELEMENT orm (result*)>
<!ATTLIST orm id CDATA #REQUIRED>
<!ATTLIST orm class CDATA #IMPLIED>
<!ATTLIST orm dbgroup CDATA "default">
<!ATTLIST orm table CDATA #IMPLIED>
<!ATTLIST orm shadow CDATA #IMPLIED>

<!ELEMENT generator (param*)>
<!ATTLIST generator class CDATA "native">

<!ELEMENT result EMPTY>
<!ATTLIST result property CDATA #REQUIRED>
<!ATTLIST result column CDATA #REQUIRED>
<!ATTLIST result type CDATA #IMPLIED>
<!ATTLIST result null CDATA #IMPLIED>
<!ATTLIST result loader CDATA #IMPLIED>

=== ryanwli/guzz/src/test/resources/guzzmain_test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//DTD MAIN CONFIG//EN" "http://www.guzz.org/dtd/guzz.dtd">

<guzz-configs>
	
	<config-server>
		<server class="org.guzz.config.LocalFileConfigServer">
			<param name="resource" value="guzz_test2.properties" />
			<param name="optionalResource" value="additional.properties" />
		</server>
	</config-server>
	
	<dialect class="org.guzz.dialect.H2Dialect"></dialect>
	<dialect name="mysql5dialect" class="org.guzz.dialect.Mysql5Dialect" />
	<dialect name="oracle10gdialect" class="org.guzz.dialect.Oracle10gDialect" />
	
	<tran>
		<dbgroup name="default" masterDBConfigName="masterDB" />
		<dbgroup name="mysql" masterDBConfigName="mysqlDB" dialectName="mysql5dialect" />
		<dbgroup name="oracle" masterDBConfigName="oracleDB" dialectName="oracle10gdialect" />
		
		<virtualdbgroup name="cargoDB" dialectName="default" shadow="org.guzz.test.shop.CargoVirtualDBView" >
			<dbgroup name="cargoDB.cargo2" masterDBConfigName="cargo2DB" />
		</virtualdbgroup>
		
		<virtualdbgroup name="commentDB" dialectName="default" shadow="org.guzz.test.CommentVirtualDBView" />
				
		<virtualdbgroup name="other" dialectName="mysql5dialect" shadow="org.guzz.test.shop.CargoVirtualDBView" />
	</tran>
	
	<service name="onlyForTest2" configName="onlyForTest2Config" dependsOn="onlyForTest" class="org.guzz.test.sample.SampleTestService2" />
	<service name="onlyForTest" configName="onlyForTestConfig" class="org.guzz.test.sample.SampleTestService" />
	<service name="guzzDynamicSQL" configName="guzzDynamicSQL" class="org.guzz.service.core.impl.FileDynamicSQLServiceImpl" />
	<service name="guzzTemplatedSQL" class="org.guzz.service.core.impl.VelocityTemplatedSQLService" />
	
	<import resource="include/part2.xml" />

	<business-scan dbgroup="cargoDB" resources="classpath*:org/guzz/test/shop/*" />
	<business name="user" dbgroup="default" class="org.guzz.test.User" interpret="" file="classpath:org/guzz/test/User.hbm.xml" />
	<business name="book" class="org.guzz.test.Book" file="classpath:org/guzz/test/Book.hbm.xml" />
	<business name="userInfo" dbgroup="oracle" class="org.guzz.test.UserInfo" file="classpath:org/guzz/test/UserInfo.hbm.xml" />
	<business name="userInfo2" dbgroup="default" file="classpath:org/guzz/test/UserInfoH2.hbm.xml" />
	<business name="comment" dbgroup="commentDB" file="classpath:org/guzz/test/Comment.hbm.xml" />
	<business name="sp" dbgroup="default" file="classpath:org/guzz/test/shop/SpecialProperty.hbm.xml" />
	
	<sqlMap dbgroup="default">
		<select id="selectUser" orm="user">
			select * from @@user
				 where 
				 	@id = :id
			
			<paramsMapping>
				<map paramName="id" type="int" />
			</paramsMapping>
		</select>
		
		<select id="selectUserByName" orm="user">
			select @id, @userName, @vip, @password from @@user where @userName = :userName
			
			<paramsMapping>
				<map paramName="userName" propName="userName" />
			</paramsMapping>
		</select>
	
		<update id="updateUserFavCount" orm="userObjectMap">
			update @@user set @favCount = favCount + 1
		</update>
	
		<select id="getCount" orm="user">
			select 30 as totalCount
		</select>
		
		<select id="selectUserByName2" orm="user" result-class="java.util.HashMap">
			select pk, userName, VIP_USER, MyPSW, FAV_COUNT from TB_USER where userName = :userName
		</select>
		
		<select id="selectUsers" orm="userObjectMap">
			select @id, @name, @vip, @favCount from @@user
		</select>
		
		<select id="listCommentsByName" orm="commentMap" templated="true">
			select * from @@commentMap
			
			#notEmpty($userName)
			 	where @userName = :userName
			#end
			
			<paramsMapping>
				<map paramName="userName" propName="userName" />
			</paramsMapping>
		</select>
				
		<orm id="userObjectMap" class="org.guzz.test.UserModel">
			<result property="id" column="pk"/>
		    <result property="name" column="userName"/>
		    <result property="favCount" column="FAV_COUNT"/>
		    <result property="vip" column="VIP_USER"/>
		</orm>
		
		<orm id="commentMap" dbgroup="commentDB" class="org.guzz.test.Comment" table="TB_COMMENT" shadow="org.guzz.test.CommentShadowView">
			<result property="id" column="id" type="int"/>
		    <result property="userId" column="userId" type="int"/>
		    <result property="userName" column="userName" type="string" />
		    <result property="createdTime" column="createdTime" type="datetime" />
		</orm>
	</sqlMap>
	
	<sqlMap dbgroup="cargoDB">
		<select id="selectCrossSize" orm="cargo" result-class="org.guzz.orm.rdms.MyCrossStitch" templated="true">
			select name, price, gridNum, size, brand from @@cargo where id > ${id}
		</select>
	</sqlMap>

</guzz-configs>

=== ryanwli/guzz/src/test/resources/guzzmain_spring.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guzz-configs PUBLIC "-//GUZZ//DTD MAIN CONFIG//EN" "http://www.guzz.org/dtd/guzz.dtd">

<guzz-configs>
	
	<config-server>
		<server class="org.guzz.config.LocalFileConfigServer">
			<param name="resource" value="guzz_test2.properties" />
			<param name="optionalResource" value="additional.properties" />
		</server>
	</config-server>
	
	<dialect class="org.guzz.dialect.H2Dialect"></dialect>
	<dialect name="mysql5dialect" class="org.guzz.dialect.Mysql5Dialect" />
	<dialect name="oracle10gdialect" class="org.guzz.dialect.Oracle10gDialect" />
	
	<tran locator="spring">
		<dbgroup name="default" masterDBConfigName="masterDB" />
		<dbgroup name="mysql" masterDBConfigName="mysqlDB" dialectName="mysql5dialect" />
		<dbgroup name="oracle" masterDBConfigName="oracleDB" dialectName="oracle10gdialect" />
		
		<virtualdbgroup name="cargoDB" dialectName="default" shadow="org.guzz.test.shop.CargoVirtualDBView" >
			<dbgroup name="cargoDB.cargo2" masterDBConfigName="cargo2DB" />
		</virtualdbgroup>
		
		<virtualdbgroup name="commentDB" dialectName="default" shadow="org.guzz.test.CommentVirtualDBView" />
		
		<virtualdbgroup name="other" dialectName="mysql5dialect" shadow="org.guzz.test.shop.CargoVirtualDBView" />
	</tran>
	
	<service name="onlyForTest" configName="onlyForTestConfig" class="org.guzz.test.sample.SampleTestService" />
	<service name="onlyForTest2" configName="onlyForTest2Config" dependsOn="onlyForTest" class="org.guzz.test.sample.SampleTestService2" />
	<service name="guzzDynamicSQL" configName="guzzDynamicSQL" class="org.guzz.service.core.impl.FileDynamicSQLServiceImpl" />
	
	<import resource="include/part2.xml" />

	<a-business name="user" dbgroup="default" class="org.guzz.test.User"/>
	<a-business name="book" class="org.guzz.test.Book" />
	<a-business name="userInfo" dbgroup="oracle" class="org.guzz.test.UserInfo" />
	<a-business name="userInfo2" dbgroup="default" class="org.guzz.test.UserInfoH2" />
	<a-business name="comment" dbgroup="commentDB" class="org.guzz.test.Comment"/>
	<a-business name="cargo" dbgroup="cargoDB" class="org.guzz.test.shop.Cargo" />
	<a-business name="sp" class="org.guzz.test.shop.SpecialProperty" />
	
	<sqlMap dbgroup="default">
		<select id="selectUser" orm="user">
			select * from @@user
			 where 
			 	@id = :id 
			
			<paramsMapping>
				<map paramName="id" type="int" />
			</paramsMapping>
		</select>
		
		<select id="selectUserByName" orm="user" result-class="java.util.HashMap">
			select @id, @userName, @vip, @password from @@user where @userName = :userName
			
			<paramsMapping>
				<map paramName="userName" propName="userName" />
			</paramsMapping>
		</select>
	
		<update id="updateUserFavCount" orm="userObjectMap">
			update @@user set @favCount = favCount + 1
		</update>
	
		<select id="getCount" orm="user">
			select 30 as totalCount
		</select>
		
		<select id="selectUserByName2" orm="user" result-class="java.util.HashMap">
			select pk, userName, VIP_USER, MyPSW, FAV_COUNT from TB_USER where userName = :userName
		</select>
		
		<select id="selectUsers" orm="userObjectMap">
			select @id, @name, @vip, @favCount from @@user
		</select>
		
		<select id="listCommentsByName" orm="commentMap" >
			select * from @@commentMap where @userName = :userName
			
			<paramsMapping>
				<map paramName="userName" propName="userName" />
			</paramsMapping>
		</select>
				
		<orm id="userObjectMap" class="org.guzz.test.UserModel">
			<result property="id" column="pk"/>
		    <result property="name" column="userName"/>
		    <result property="favCount" column="FAV_COUNT"/>
		    <result property="vip" column="VIP_USER"/>
		</orm>
		
		<orm id="commentMap" dbgroup="commentDB" class="org.guzz.test.Comment" table="TB_COMMENT" shadow="org.guzz.test.CommentShadowView">
			<result property="id" column="id" type="int"/>
		    <result property="userId" column="userId" type="int"/>
		    <result property="userName" column="userName" type="string" />
		    <result property="createdTime" column="createdTime" type="datetime" />
		</orm>
	</sqlMap>
	
	<sqlMap dbgroup="cargoDB">
		<select id="selectCrossSize" orm="cargo" result-class="org.guzz.orm.rdms.MyCrossStitch">
			select name, price, gridNum, size, brand from @@cargo where id > :id
		</select>
	</sqlMap>

</guzz-configs>
